### ISSUE TITLE
Prediction gives only one class

### ISSUE THREAD

**Issue by vigneshprajapati** [zygmuntz/pybrain-practice#1]
While running kin_predict.py with test datasets, its giving negative probabilities. Anad making them round gives only single class prediction.

**Comment by zygmuntz** [comment]
You do realize kin8nm is a regression dataset, don't you?

**Comment by vigneshprajapati** [comment]
Oh. Yes. I got this. Can you suggest me some pointers to perform Neural Network over Binary classification dataset ?

**Comment by zygmuntz** [comment]
Pretty much every NN package is able to classify, incl. PyBrain. Another one in pure Python: https://github.com/HIPS/Kayak
